import {STORE_KEY, APP_VERSION, methods, processes, uid, today, defaults, load, persist} from './data.js';
import {criteria, renderStars, collectCriteria, criteriaChips, methodAverages, starText} from './ratings.js';
let db = load(); let editing = null; let currentAdvice = '';
const $ = s => document.querySelector(s);
const esc = (s='') => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const byId = (col,id)=>(db[col]||[]).find(x=>x.id===id);
function save(){ persist(db); render(); }
async function photoToDataUrl(file){
  if(!file || !file.name) return '';
  return new Promise(resolve=>{ const img=new Image(); const reader=new FileReader();
    reader.onload=()=>{ img.onload=()=>{ const max=1200, scale=Math.min(1,max/Math.max(img.width,img.height)); const c=document.createElement('canvas'); c.width=Math.round(img.width*scale); c.height=Math.round(img.height*scale); const ctx=c.getContext('2d'); ctx.drawImage(img,0,0,c.width,c.height); resolve(c.toDataURL('image/jpeg',.82)); }; img.onerror=()=>resolve(reader.result); img.src=reader.result; };
    reader.onerror=()=>resolve(''); reader.readAsDataURL(file);
  });
}
function openAdd(dialogId){ editing=null; const form = $('#'+dialogId+' form'); if(form) {form.reset(); form.querySelector('[data-title]') && (form.querySelector('[data-title]').textContent=form.querySelector('[data-title]').textContent.replace('Modifier','Ajouter'));} renderSelects(); renderCriteriaInputs({}); $('#'+dialogId).showModal(); }
window.editItem = (collection,id)=>{ const item=byId(collection,id); if(!item) return; editing={collection,id}; renderSelects(); const dialogId={brews:'brewForm',coffees:'coffeeForm',recipes:'recipeForm',grinders:'grinderForm',machines:'machineForm'}[collection]; const form=$('#'+dialogId+' form'); form.reset(); form.querySelector('[data-title]') && (form.querySelector('[data-title]').textContent='Modifier'); [...form.elements].forEach(el=>{ if(!el.name || el.type==='file') return; if(item[el.name]!==undefined) el.value=item[el.name]; }); if(collection==='brews') renderCriteriaInputs(item.criteria||{}); $('#'+dialogId).showModal(); };
window.removeItem = (collection,id)=>{ if(confirm('Supprimer cet élément ?')){ db[collection]=db[collection].filter(x=>x.id!==id); save(); } };
function itemActions(col,id,extra=''){return `<div class="item-actions">${extra}<button class="ghost" onclick="editItem('${col}','${id}')">Modifier</button><button class="ghost" onclick="removeItem('${col}','${id}')">Supprimer</button></div>`}
function renderSelects(){
  $('#brewEditor [name="coffeeId"]').innerHTML=db.coffees.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');
  $('#brewEditor [name="method"]').innerHTML=methods.map(m=>`<option>${m}</option>`).join('');
  $('#recipeEditor [name="method"]').innerHTML=methods.map(m=>`<option>${m}</option>`).join('');
  $('#brewEditor [name="grinderId"]').innerHTML='<option value="">Moulin</option>'+db.grinders.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('');
  $('#brewEditor [name="machineId"]').innerHTML='<option value="">Machine</option>'+db.machines.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('');
  $('#coffeeEditor [name="process"]').innerHTML='<option value="">Process</option>'+processes.map(p=>`<option>${p}</option>`).join('');
}
function renderCriteriaInputs(values={}){ $('#brewCriteria').innerHTML=criteria.map(c=>`<div class="rating-line"><div><div class="criterion-title">${esc(c.label)} <button class="info-btn" data-help="${c.key}" type="button">i</button></div><p class="muted small-text">${esc(c.short)}</p></div>${renderStars('criteria_'+c.key, values[c.key]||'')}</div>`).join(''); bindRatingControls(); }
function bindRatingControls(){ document.querySelectorAll('.stars .star').forEach(btn=>btn.onclick=()=>{ const wrap=btn.closest('.stars'); const input=wrap.querySelector('input'); const v=btn.dataset.value; input.value = input.value===v ? '' : v; wrap.querySelectorAll('.star').forEach(s=>s.classList.toggle('on', Number(s.dataset.value)<=Number(input.value))); }); document.querySelectorAll('[data-help]').forEach(b=>b.onclick=()=>showHelp(b.dataset.help)); }
function showHelp(key){ const c=criteria.find(x=>x.key===key); if(!c) return; $('#helpTitle').textContent=c.help.title; $('#helpBody').innerHTML=`<h3>Définition</h3><p>${esc(c.help.definition)}</p><h3>À ne pas confondre</h3><p>${esc(c.help.confusion)}</p><h3>Exemples</h3><ul>${c.help.examples.map(e=>`<li>${esc(e)}</li>`).join('')}</ul><h3>La bonne question</h3><p><strong>${esc(c.short)}</strong></p>`; $('#helpModal').showModal(); }
function renderLast(){ const last=db.brews[db.brews.length-1]; if(!last){$('#lastBrewTitle').textContent='Aucune extraction';$('#lastBrewMeta').textContent='Ajoute ton premier café ou ta première extraction.';$('#lastBrewScore').textContent='';return;} const coffee=byId('coffees',last.coffeeId)?.name||'Café'; const grinder=byId('grinders',last.grinderId)?.name||'Moulin'; $('#lastBrewTitle').textContent=`${last.method} — ${coffee}`; $('#lastBrewMeta').textContent=`${last.dose||'?'}g → ${last.yield||'?'}g · ${last.time||'?'}s · ${grinder} · ${last.grind||'réglage ?'}`; $('#lastBrewScore').textContent=starText(last.rating); }
function renderBrews(){ const items=[...db.brews].reverse(); $('#brewList').innerHTML=items.map(b=>{ const coffee=byId('coffees',b.coffeeId)?.name||'Café supprimé'; const grinder=byId('grinders',b.grinderId)?.name||''; const machine=byId('machines',b.machineId)?.name||''; const chips=criteriaChips(b.criteria); return `<article class="item">${b.photo?`<img class="photo" src="${b.photo}" alt="Photo extraction">`:''}<div class="item-top"><strong>${esc(b.method)} — ${esc(coffee)}</strong>${b.rating?`<span class="pill">${starText(b.rating)}</span>`:''}</div><p>${esc(b.dose||'?')}g → ${esc(b.yield||'?')}g · ${esc(b.time||'?')}s · ${esc(b.grind||'réglage ?')}</p>${(grinder||machine)?`<p class="muted">${esc([grinder,machine].filter(Boolean).join(' · '))}</p>`:''}${chips?`<div class="criteria-view">${chips}</div>`:''}${b.notes?`<p>${esc(b.notes)}</p>`:''}${itemActions('brews',b.id,`<button class="ghost" onclick="openTaste('${b.id}')">Compass</button>`)}</article>`}).join('') || '<p class="muted">Aucune extraction pour l’instant.</p>'; }
function renderCoffees(){ $('#coffeeList').innerHTML=db.coffees.map(c=>{ const avgs=methodAverages(db,c.id); const methodHtml=avgs.map(a=>`<span class="rating-chip">${esc(a.method)} ${starText(Math.round(a.avg))} <small>(${a.count})</small></span>`).join(''); return `<article class="item">${c.photo?`<img class="photo" src="${c.photo}" alt="${esc(c.name)}">`:''}<div class="item-top"><strong>${esc(c.name)}</strong>${c.repurchaseRating?`<span class="pill">Rachat ${starText(c.repurchaseRating)}</span>`:''}</div>${[c.roaster,c.origin,c.process,c.roast].filter(Boolean).length?`<p class="muted">${esc([c.roaster,c.origin,c.process,c.roast].filter(Boolean).join(' · '))}</p>`:''}${methodHtml?`<div><p class="eyebrow">Par méthode</p><div class="method-ratings">${methodHtml}</div></div>`:''}${c.notes?`<p>${esc(c.notes)}</p>`:''}${itemActions('coffees',c.id)}</article>`}).join('') || '<p class="muted">Aucun café.</p>'; }
function renderRecipes(){ $('#recipeList').innerHTML=db.recipes.map(r=>`<article class="item"><div class="item-top"><strong>${esc(r.name)}</strong>${r.method?`<span class="pill">${esc(r.method)}</span>`:''}</div>${r.source?`<p class="muted">${esc(r.source)}</p>`:''}${r.guide?`<p>${esc(r.guide).replaceAll('\n','<br>')}</p>`:''}${r.video?`<a href="${esc(r.video)}" target="_blank" rel="noreferrer">Voir la vidéo</a>`:''}${itemActions('recipes',r.id)}</article>`).join('')||'<p class="muted">Aucune recette.</p>'; }
function renderGear(){ $('#grinderList').innerHTML=db.grinders.map(g=>`<article class="item"><div class="item-top"><strong>${esc(g.name)}</strong>${g.unit?`<span class="pill">${esc(g.unit)}</span>`:''}</div>${g.notes?`<p class="muted">${esc(g.notes)}</p>`:''}${itemActions('grinders',g.id)}</article>`).join(''); $('#machineList').innerHTML=db.machines.map(m=>`<article class="item"><div class="item-top"><strong>${esc(m.name)}</strong>${m.type?`<span class="pill">${esc(m.type)}</span>`:''}</div>${m.notes?`<p class="muted">${esc(m.notes)}</p>`:''}${itemActions('machines',m.id)}</article>`).join(''); }
function render(){ renderSelects(); renderLast(); renderBrews(); renderCoffees(); renderRecipes(); renderGear(); }
async function handleForm(id,collection,mapper){ const form=$('#'+id); form.addEventListener('submit',async e=>{ e.preventDefault(); const fd=new FormData(form); const fresh=await mapper(fd); if(editing&&editing.collection===collection) db[collection]=db[collection].map(x=>x.id===editing.id?{...x,...fresh,id:editing.id}:x); else db[collection].push({id:uid(),...fresh}); editing=null; form.reset(); form.closest('dialog').close(); save(); }); }
handleForm('brewEditor','brews',async fd=>({date:today(),coffeeId:fd.get('coffeeId'),method:fd.get('method'),grinderId:fd.get('grinderId'),machineId:fd.get('machineId'),dose:fd.get('dose'),yield:fd.get('yield'),time:fd.get('time'),grind:fd.get('grind'),water:fd.get('water'),rating:fd.get('rating'),criteria:collectCriteria(fd),notes:fd.get('notes'),photo:(await photoToDataUrl(fd.get('photo'))) || (editing?byId('brews',editing.id)?.photo||'':'')}));
handleForm('coffeeEditor','coffees',async fd=>({name:fd.get('name'),roaster:fd.get('roaster'),origin:fd.get('origin'),process:fd.get('process'),roast:fd.get('roast'),repurchaseRating:fd.get('repurchaseRating'),notes:fd.get('notes'),photo:(await photoToDataUrl(fd.get('photo'))) || (editing?byId('coffees',editing.id)?.photo||'':'')}));
handleForm('recipeEditor','recipes',async fd=>({name:fd.get('name'),method:fd.get('method'),source:fd.get('source'),video:fd.get('video'),guide:fd.get('guide')}));
handleForm('grinderEditor','grinders',async fd=>({name:fd.get('name'),unit:fd.get('unit'),notes:fd.get('notes')}));
handleForm('machineEditor','machines',async fd=>({name:fd.get('name'),type:fd.get('type'),notes:fd.get('notes')}));
document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$('#'+btn.dataset.tab).classList.add('active');});
document.querySelectorAll('[data-open]').forEach(btn=>btn.onclick=()=>openAdd(btn.dataset.open)); $('#quickAddBtn').onclick=()=>openAdd('brewForm');
const compassAdvice={sour:'Acide/piquant : moudre plus fin, augmenter un peu le rendement ou la température.',bitter:'Amer : moudre plus gros, réduire le rendement ou baisser un peu la température.',dry:'Sec/astringent : vérifier WDT, répartition, tassage, puis réduire un peu le rendement.',watery:'Aqueux : réduire la sortie, augmenter la dose ou moudre plus fin si le shot est rapide.',channel:'Acide + amer : probable channeling, travailler la préparation du puck.'};
$('#compassNodes').innerHTML=Object.entries({sour:'Acide',bitter:'Amer',dry:'Sec',watery:'Aqueux',channel:'Acide + amer'}).map(([k,v])=>`<button class="compass-node" data-problem="${k}">${v}</button>`).join('');
document.querySelectorAll('[data-problem]').forEach(btn=>btn.onclick=()=>{currentAdvice=compassAdvice[btn.dataset.problem]; $('#tasteAdvice').textContent=currentAdvice;});
window.openTaste=(brewId='')=>{ if(brewId) editing={collection:'brews',id:brewId}; currentAdvice=''; $('#tasteAdvice').textContent='Choisis une zone.'; $('#tasteModal').showModal(); };
document.querySelectorAll('[data-taste-open]').forEach(btn=>btn.onclick=()=>openTaste(editing?.id||''));
$('#appendAdviceBtn').onclick=()=>{ if(!currentAdvice) return; const ta=$('#brewEditor [name="notes"]'); if($('#brewForm').open&&ta) ta.value=[ta.value,currentAdvice].filter(Boolean).join('\n'); else if(editing?.collection==='brews'){ const b=byId('brews',editing.id); if(b){ b.notes=[b.notes,currentAdvice].filter(Boolean).join('\n'); save(); }} $('#tasteModal').close(); };
$('#exportBtn').onclick=()=>{ const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`brewbook-export-${today()}.json`; a.click(); URL.revokeObjectURL(a.href); };
$('#importInput').onchange=e=>{ const file=e.target.files[0]; if(!file) return; const r=new FileReader(); r.onload=()=>{try{ const imported=JSON.parse(r.result); if(!imported.coffees||!imported.brews) throw new Error(); db=imported; save(); alert('Import terminé.');}catch{alert('Fichier JSON invalide.');}}; r.readAsText(file); };
$('#resetBtn').onclick=()=>{ if(confirm('Remettre les données de démo ?')){ db=structuredClone(defaults); save(); } };
$('#forceRefreshBtn').onclick=async()=>{ try{ if('serviceWorker' in navigator){const regs=await navigator.serviceWorker.getRegistrations(); await Promise.all(regs.map(r=>r.unregister()));} if('caches' in window){const keys=await caches.keys(); await Promise.all(keys.map(k=>caches.delete(k)));} }catch{} location.href=location.href.split('?')[0]+'?'+APP_VERSION+'-'+Date.now(); };
const tip=$('#installTip'); if(!localStorage.getItem('brewbook.installTip.closed') && !matchMedia('(display-mode: standalone)').matches){ tip.hidden=false; } $('#closeInstallTip').onclick=()=>{localStorage.setItem('brewbook.installTip.closed','1'); tip.hidden=true;};
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js?v=0.7').catch(()=>{});
renderCriteriaInputs({}); render();
