export const criteria = [
  {key:'taste', label:'Goût', short:'Est-ce que la tasse te plaît globalement ?', help:{title:'Goût', definition:'La note la plus simple : est-ce que c’est bon pour toi, dans cette recette et à ce moment-là ?', confusion:'Ce n’est pas une note technique. Un café très léger ou très dense peut avoir 5 étoiles si tu l’aimes.', examples:['1 étoile : tu n’as pas envie de finir la tasse.','3 étoiles : c’est correct, sans coup de cœur.','5 étoiles : tu as envie de refaire exactement cette tasse.']}},
  {key:'balance', label:'Équilibre', short:'Est-ce qu’un élément prend trop de place ?', help:{title:'Équilibre', definition:'Un café équilibré donne l’impression que rien ne hurle plus fort que le reste.', confusion:'À ne pas confondre avec “neutre”. Un café peut être très fruité et rester équilibré.', examples:['Trop acide, trop amer ou trop sec : équilibre faible.','Fruité, doux, amer et texture bien intégrés : équilibre élevé.']}},
  {key:'acidity', label:'Acidité', short:'Est-ce que la vivacité rend le café agréable ?', help:{title:'Acidité', definition:'La vivacité du café. Elle peut rappeler citron, pomme verte, orange, fruits rouges ou pêche.', confusion:'À ne pas confondre avec l’amertume, qui tire vers chocolat noir/cacao et reste souvent plus longtemps. Une acidité agressive peut aussi signaler une sous-extraction.', examples:['Bonne acidité : fraîche, fruitée, donne envie de revenir.','Mauvaise acidité : pique, serre la mâchoire, paraît verte ou salée.']}},
  {key:'bitterness', label:'Amertume', short:'Est-ce que l’amertume participe au plaisir ?', help:{title:'Amertume', definition:'Sensation proche du cacao, chocolat noir, zeste ou IPA. Un peu d’amertume peut être très agréable.', confusion:'À ne pas confondre avec acidité. L’amertume est plus sombre, souvent persistante. Brûlé/cendré n’est pas juste “amer”.', examples:['Bonne amertume : cacao, chocolat noir, structure.','Mauvaise amertume : brûlé, cendre, médicament, bouche sèche.']}},
  {key:'sweetness', label:'Douceur', short:'Est-ce qu’il y a une sensation douce/sucrée ?', help:{title:'Douceur', definition:'Impression sucrée sans sucre ajouté : miel, caramel, fruit mûr, chocolat au lait.', confusion:'Ce n’est pas forcément “pas acide”. Un café peut être acide et très doux, comme certains fruits mûrs.', examples:['Faible : tasse dure, verte ou creuse.','Élevée : rondeur, fruit mûr, sensation agréable.']}},
  {key:'clarity', label:'Clarté', short:'Est-ce que tu distingues facilement les goûts ?', help:{title:'Clarté', definition:'Capacité à identifier les saveurs séparément : floral, agrume, fruit, chocolat, etc.', confusion:'Une clarté faible n’est pas automatiquement mauvaise. Certains espressos sont volontairement fondus, chocolatés, denses.', examples:['Clarté élevée : plusieurs notes faciles à nommer.','Clarté faible : tout se mélange, mais ça peut rester très bon.']}},
  {key:'body', label:'Corps', short:'Est-ce que la texture te plaît ?', help:{title:'Corps', definition:'Sensation de poids et texture en bouche : léger, juteux, velouté, sirupeux, crémeux.', confusion:'Ne note pas “plus c’est lourd mieux c’est”. Note si cette texture te plaît pour cette tasse.', examples:['Un filtre très léger peut avoir 5 étoiles.','Un espresso sirupeux peut avoir 5 étoiles. Le critère juge ton plaisir, pas la masse.']}},
  {key:'finish', label:'Longueur', short:'Est-ce que l’après-goût est agréable ?', help:{title:'Longueur', definition:'Ce qui reste après avoir avalé : arômes, douceur, fraîcheur, amertume, sécheresse.', confusion:'Long n’est pas toujours mieux. Un goût brûlé qui reste longtemps est une mauvaise longueur.', examples:['Bonne longueur : fruit, sucre, chocolat propre.','Mauvaise longueur : cendre, carton, sécheresse, médicament.']}}
];
export const starText = n => n ? '★★★★★'.slice(0, Number(n)) : '';
export function renderStars(name, value=''){
  return `<div class="stars" data-rating="${name}">${[1,2,3,4,5].map(n=>`<button class="star ${Number(value)>=n?'on':''}" type="button" data-value="${n}" aria-label="${n} étoiles">★</button>`).join('')}<input type="hidden" name="${name}" value="${value||''}"></div>`;
}
export function collectCriteria(fd){ const out={}; criteria.forEach(c=>{ const v=fd.get('criteria_'+c.key); if(v) out[c.key]=v; }); return out; }
export function criteriaChips(obj={}){ return criteria.filter(c=>obj[c.key]).map(c=>`<span class="rating-chip">${c.label} ${starText(obj[c.key])}</span>`).join(''); }
export function methodAverages(db, coffeeId){
  const rows = db.brews.filter(b=>b.coffeeId===coffeeId && b.rating);
  const by = {};
  rows.forEach(b=>{ by[b.method] ||= []; by[b.method].push(Number(b.rating)); });
  return Object.entries(by).map(([method,vals])=>({method,avg: vals.reduce((a,b)=>a+b,0)/vals.length,count:vals.length})).sort((a,b)=>b.avg-a.avg);
}
